spring.application.name=rabbitmq_demo

spring.main.allow-circular-references=true

server.port=8083

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=root
spring.rabbitmq.password=root123

# producer reconnect 作用於 rabbitTemplate 不需手動設定
#spring.rabbitmq.connection-timeout=1000s
## timeout retry open
#spring.rabbitmq.template.retry.enabled=true
## 失敗後的初始等待時間
#spring.rabbitmq.template.retry.initial-interval=1000ms
## 失敗後下次的等待時長倍數 initial-interval*multiplier
#spring.rabbitmq.template.retry.multiplier=1
## 最大重試次數
#spring.rabbitmq.template.retry.max-attempts=10


#如果手動定義 connectionFactory 會吃不到這裡的設定 與上方作用域不同
## 開啟 publisher-confirm 使用非同步通知 同步為simple會阻塞消息
#spring.rabbitmq.publisher-confirm-type=correlated
## 開啟 publisher-returns 機制 路由失敗才會返回 一般情況不需要
#spring.rabbitmq.publisher-returns=false

# consumer
spring.rabbitmq.listener.simple.acknowledge-mode=auto
# 同一時間最多給 consumer 一條消息
spring.rabbitmq.listener.simple.prefetch=1
## 開啟消費者失敗重試模式
spring.rabbitmq.listener.simple.retry.enabled=true
## 初始的失敗等待時長為1s
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
## 下次等待時長倍數 下次等待時長＝multiplier * last-interval
spring.rabbitmq.listener.simple.retry.multiplier=1
## 最大重試次數
spring.rabbitmq.listener.simple.retry.max-attempts=5
## true 無狀態 false 有狀態，有事務的話請用false
spring.rabbitmq.listener.simple.retry.stateless=true




## db
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=PostTest01
spring.datasource.driver-class-name=org.postgresql.Driver
